### ISSUE TITLE
cannot use cli (type *"github.com/go-redis/redis".Client) as type *"github.com/nitishm/go-rejson/vendor/github.com/go-redis/redis".Client in argument to rh.SetGoRedisClientgo

### ISSUE THREAD

**Issue by tghastings** [nitishm/go-rejson#30] opened 2019-04-03 21:14 UTC
Error:  cannot use cli (type *"github.com/go-redis/redis".Client) as type *"github.com/nitishm/go-rejson/vendor/github.com/go-redis/redis".Client in argument to rh.SetGoRedisClientgo

When trying to run example code on like 97: 

	rh.SetGoRedisClient(cli)

**Comment by ccaum** [comment] 2019-04-11 04:19
Same error here.

**Comment by nitishm** [comment] 2019-04-16 23:29
@tghastings @ccaum Thanks for reporting this problem. Will address is it as soon as I can.

**Comment by tghastings** [comment] 2019-04-18 14:21
@nitishm, When you fix it could you let me know how? I've been looking at it and they should both be the same type so I'm not sure why they're not.

**Comment by nitishm** [comment] 2019-04-19 23:59
@tghastings , @ccaum When you say example code is this referring to the https://github.com/nitishm/go-rejson/blob/master/examples/json_set/json_set.go ?

**Comment by HayTran94** [comment] 2019-05-22 03:12
> Error: cannot use cli (type *"github.com/go-redis/redis".Client) as type *"github.com/nitishm/go-rejson/vendor/github.com/go-redis/redis".Client in argument to rh.SetGoRedisClientgo
> 
> When trying to run example code on like 97:
> 
> ```
> rh.SetGoRedisClient(cli)
> ```

You can delete `github.com/nitishm/go-rejson/vendor/*` folder, and simple use it

**Comment by nicfb** [comment] 2019-08-07 12:17
@nitishm - If the solution here was removing the contents of the vendor directory, and that directory was removed when we swapped over to Go Modules, is there anything else that needs to be done here? Or is this a part of a larger underlying problem?

**Comment by nitishm** [comment] 2019-08-07 13:46
@nicfb I think the go module switch should solve this problem. Honestly I couldnt reproduce this problem on my own system. But I think it's fair to close this issue with the switch to go modules. I do however want to tag the latest master as v2.1.0, which I will later today.

**Closed by nitishm** 2019-08-07 13:46 UTC
